import { useState, type FormEvent } from 'react'
import { bytes, date, go, modeName, number, short, titleCase, useResource, type AcceleratorSample, type Application, type DiagnosisRow, type HostWindow, type Provider, type RuntimeWindow } from './data'
import { Empty, ErrorView, Heading, KV, Loading, Panel } from './ui'

export function Providers(){
  const {data,loading,error,reload}=useResource<{providers:Provider[]}>('/api/providers')
  const [id,setID]=useState('')
  const [name,setName]=useState('')
  const [mode,setMode]=useState<'external'|'self_hosted'>('external')
  const [baseURL,setBaseURL]=useState('')
  const [apiKeyEnv,setAPIKeyEnv]=useState('')
  const [message,setMessage]=useState('')
  const [saving,setSaving]=useState(false)
  async function create(e:FormEvent){
    e.preventDefault();setSaving(true);setMessage('')
    try{
      const response=await fetch('/api/providers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id.trim(),name:name.trim(),mode,base_url:baseURL.trim(),api_key_env:apiKeyEnv.trim()})})
      const result=await response.json()
      if(!response.ok)throw new Error(result.error||'Could not add provider')
      setID('');setName('');setBaseURL('');setAPIKeyEnv('');setMessage('Provider added. It is now available in Test Lab.');reload()
    }catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{setSaving(false)}
  }
  return <div className="page"><Heading eyebrow="CONFIGURATION / PROVIDERS" title="Provider catalog" description="Configured inference routes and the telemetry each can expose."/>
    {loading?<Loading/>:error?<ErrorView message={error}/>:<div className="provider-grid">{data?.providers.map(p=><div className="provider-card" key={p.id}><div className="provider-top"><span className="provider-avatar">{p.name.slice(0,1)}</span><span className={'pill '+(p.enabled?'good':'neutral')}>{p.enabled?'Configured':'Not configured'}</span></div><h2>{p.name}</h2><p>{modeName(p.mode)} · {p.id}</p><div className="capabilities">{Object.entries(p.capabilities).map(([key,value])=><span className={value?'supported':'unsupported'} key={key}>{value?'✓':'·'} {titleCase(key)}</span>)}</div></div>)}</div>}
    <Panel title="Add provider" subtitle="Add an OpenAI-compatible API or self-hosted runtime">
      <form className="form" onSubmit={create}>
        <label>Provider ID<input required maxLength={40} pattern="[a-z][a-z0-9_]+" placeholder="my_provider" value={id} onChange={e=>setID(e.target.value)}/></label>
        <label>Name<input required maxLength={100} placeholder="My provider" value={name} onChange={e=>setName(e.target.value)}/></label>
        <label>Mode<select value={mode} onChange={e=>setMode(e.target.value as 'external'|'self_hosted')}><option value="external">External</option><option value="self_hosted">Self-hosted</option></select></label>
        <label>API base URL<input required type="url" placeholder="https://api.example.com/v1" value={baseURL} onChange={e=>setBaseURL(e.target.value)}/></label>
        <label>API key environment variable<input placeholder="MY_PROVIDER_API_KEY (optional)" value={apiKeyEnv} onChange={e=>setAPIKeyEnv(e.target.value)}/></label>
        <p className="footnote">The key value stays in the backend environment. Export the named variable before starting the API. Providers added here must support OpenAI-compatible chat requests.</p>
        <button className="primary" type="submit" disabled={saving}>{saving?'Adding…':'Add provider'}</button>
        {message&&<small>{message}</small>}
      </form>
    </Panel>
  </div>
}
export function Infrastructure(){const {data,loading,error}=useResource<{request_id?:string;provider?:string;host:HostWindow|null;runtime:RuntimeWindow|null;accelerators:AcceleratorSample[];accelerator_error?:string}>('/api/infrastructure');const last=data?.host?.samples.at(-1);return <div className="page"><Heading eyebrow="OBSERVABILITY / INFRASTRUCTURE" title="Infrastructure signals" description="Latest request-correlated host and runtime observations. Server-wide counters are labeled as such."/>{loading?<Loading/>:error?<ErrorView message={error}/>:<><div className="grid-two"><Panel title="Host" subtitle={data?.request_id?`From request ${short(data.request_id)}`:'No self-hosted request yet'}>{last?<div className="latency-list"><KV label="Host CPU" value={last.cpu_utilization_pct==null?'—':`${number(last.cpu_utilization_pct)}%`}/><KV label="Process CPU" value={last.process_cpu_pct==null?'—':`${number(last.process_cpu_pct)}%`}/><KV label="Available RAM" value={bytes(last.host_available_bytes)}/><KV label="Process RSS" value={bytes(last.process_rss_bytes)}/><KV label="Threads" value={last.threads?.toString()??'—'}/><KV label="Load average" value={number(last.load_1)}/></div>:<Empty title="No host samples" description="Host measurements appear after a self-hosted inference request."/>}</Panel><Panel title="Runtime" subtitle={data?.provider||'Waiting for a connected runtime'}>{data?.runtime?<div className="latency-list"><KV label="Queue depth peak" value={data.runtime.peak_queue_depth?.toString()??'—'}/><KV label="Running requests" value={data.runtime.end?.running_requests?.toString()??'—'}/><KV label="KV cache use" value={data.runtime.end?.kv_cache_usage_fraction==null?'—':`${(data.runtime.end.kv_cache_usage_fraction*100).toFixed(1)}%`}/></div>:<Empty title="No runtime samples" description="Configure a runtime metrics URL to inspect queue and cache behavior."/>}</Panel></div><Panel title="Accelerators" subtitle="NVIDIA device-wide samples correlated with the latest request">{data?.accelerators?.length?<div className="latency-list">{data.accelerators.map((gpu,i)=><div key={`${gpu.device_id}-${i}`}><h3>{gpu.device_name||gpu.device_id} · {date(gpu.at)}</h3><KV label="GPU utilization" value={gpu.gpu_utilization==null?"—":`${number(gpu.gpu_utilization)}%`}/><KV label="Memory utilization" value={gpu.memory_utilization==null?"—":`${number(gpu.memory_utilization)}%`}/><KV label="VRAM used / total" value={`${bytes(gpu.vram_used_bytes)} / ${bytes(gpu.vram_total_bytes)}`}/><KV label="Temperature" value={gpu.temperature_c==null?"—":`${number(gpu.temperature_c)} °C`}/><KV label="Power" value={gpu.power_watts==null?"—":`${number(gpu.power_watts)} W`}/></div>)}</div>:<Empty title="No accelerator samples" description="NVIDIA samples appear when nvidia-smi detects a GPU and a self-hosted request runs."/>}{data?.accelerator_error&&<div className="notice">{data.accelerator_error}</div>}</Panel></>}</div>}
export function Diagnoses(){const {data,loading,error}=useResource<{diagnoses:DiagnosisRow[]}>('/api/diagnoses');return <div className="page"><Heading eyebrow="INTELLIGENCE / DIAGNOSES" title="Evidence-led findings" description="Deterministic diagnoses generated from observed request and infrastructure signals."/>{loading?<Loading/>:error?<ErrorView message={error}/>:data?.diagnoses.length?<div className="diagnosis-list">{data.diagnoses.map(d=><button key={d.id} className="diagnosis-card" onClick={()=>go('/requests/'+d.request_id)}><span className="mini-icon warning">!</span><span><strong>{d.summary}</strong><small>{d.provider} · {d.model} · {date(d.created_at)}</small><p>{d.root_cause}</p></span><span className="confidence">{Math.round(d.confidence*100)}%<small>confidence</small></span></button>)}</div>:<Empty title="No diagnoses yet" description="A finding appears only when a request supplies enough evidence for a rule."/>}</div>}
export function Settings(){const {data,reload,loading,error}=useResource<{applications:Application[]}>('/api/applications');const [name,setName]=useState('');const [description,setDescription]=useState('');const [message,setMessage]=useState('');async function create(e:FormEvent){e.preventDefault();setMessage('');const res=await fetch('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,description})});if(!res.ok){setMessage('Could not create application. Check the name and try again.');return}setName('');setDescription('');reload();setMessage('Application created.')}return <div className="page"><Heading eyebrow="WORKSPACE / SETTINGS" title="Applications & setup" description="Organize requests by application and connect your clients to the gateway."/><div className="grid-two"><Panel title="Applications" subtitle="Use application_id in your inference request">{loading?<Loading/>:error?<ErrorView message={error}/>:data?.applications.length?<div className="compact-list">{data.applications.map(a=><div className="application-row" key={a.id}><span className="mini-icon">A</span><span><strong>{a.name}</strong><small>{a.description||'No description'}</small></span><span className="list-right mono">ID {a.id}</span></div>)}</div>:<Empty title="No applications yet" description="Create one to group requests from a client or agent."/>}<form className="form" onSubmit={create}><h3>Add application</h3><input required maxLength={100} placeholder="Application name" value={name} onChange={e=>setName(e.target.value)}/><input maxLength={300} placeholder="Description (optional)" value={description} onChange={e=>setDescription(e.target.value)}/><button className="primary" type="submit">Create application</button>{message&&<small>{message}</small>}</form></Panel><Panel title="Gateway connection" subtitle="OpenAI-compatible chat endpoint"><div className="connection"><KV label="API base" value="http://127.0.0.1:8000"/><KV label="Endpoint" value="POST /v1/chat/completions"/><KV label="Database" value="SQLite · auto-created"/></div><pre>{'curl http://127.0.0.1:8000/v1/chat/completions -H "Content-Type: application/json" -d \u0027{"provider":"YOUR_PROVIDER","model":"YOUR_MODEL","messages":[{"role":"user","content":"YOUR_PROMPT"}]}\u0027'}</pre><p className="footnote">Prompts and generated text are not stored. Only metadata and collector samples are persisted.</p></Panel></div></div>}
