import type { ReactNode } from 'react'
import Link from 'next/link'
import { useResource, type Hour } from './data'

export const navigation=[['overview','Overview'],['test','Test Lab'],['requests','Requests'],['providers','Providers'],['infrastructure','Infrastructure'],['diagnoses','Diagnoses'],['settings','Settings']]
function Icon({name}:{name:string}){const paths:Record<string,string>={overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',test:'M7 3v7l-4 8a2 2 0 0 0 2 3h14a2 2 0 0 0 2-3l-4-8V3 M6 3h12 M8 15h8',requests:'M4 5h16 M4 10h16 M4 15h16 M4 20h11',providers:'M12 2l8 4.5v11L12 22l-8-4.5v-11z M4 6.5l8 4.5 8-4.5 M12 11v11',infrastructure:'M4 4h16v5H4z M4 14h16v6H4z M8 6.5h.01 M8 17h.01',diagnoses:'M12 3l10 18H2z M12 9v5 M12 18h.01',settings:'M4 7h16 M4 17h16 M8 4v6 M16 14v6'};return <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name]} /></svg>}
export function Frame({route,children}:{route:string;children:ReactNode}){const health=useResource<{status:string}>('/api/health');return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-symbol"><span /></div><div><strong>AI PROSPECTOR</strong><small>Inference intelligence</small></div></div><div className="nav-label">WORKSPACE</div><nav>{navigation.map(([id,label])=><Link key={id} href={'/'+id} className={(route==='/'&&id==='overview')||route.startsWith('/'+id)?'nav active':'nav'}><Icon name={id}/><span>{label}</span>{id==='overview'&&<span className="nav-arrow">↗</span>}</Link>)}</nav><div className="sidebar-bottom"><div className="status"><span className={'status-dot '+(health.data?'online':'offline')}/><div><strong>{health.data?'Gateway online':'Gateway offline'}</strong><small>{health.data?'Connected to local API':'Start the Go server'}</small></div></div><div className="sidebar-caption">LOCAL WORKSPACE <span>v0.1</span></div></div></aside><main className="main"><header className="topbar"><span className="breadcrumb">Workspace <span>/</span> {(route==='/'?'Overview':navigation.find(([id])=>route.startsWith('/'+id))?.[1])||'Request detail'}</span><div className="top-actions"><span className="environment">● LOCAL ENVIRONMENT</span><button className="icon-button" title="Refresh page" onClick={()=>location.reload()}>↻</button></div></header>{children}</main></div>}
export function Heading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:ReactNode}){return <div className="heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</div>}
export function Loading(){return <div className="message"><span className="spinner"/> Loading live data…</div>}
export function ErrorView({message}:{message:string}){return <div className="message error"><strong>Could not load data</strong><span>{message}</span><span>Check that the API is running on port 8000.</span></div>}
export function Empty({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="empty"><div className="empty-icon">⌁</div><strong>{title}</strong><p>{description}</p>{action}</div>}
export function Stat({label,value,hint,accent}:{label:string;value:string;hint?:string;accent?:string}){return <div className="stat"><span>{label}</span><strong className={accent||''}>{value}</strong><small>{hint||'Last 24 hours'}</small></div>}
export function Panel({title,subtitle,children,action,className=''}:{title:string;subtitle?:string;children:ReactNode;action?:ReactNode;className?:string}){return <section className={'panel '+className}><div className="panel-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>{children}</section>}
export function KV({label,value,source}:{label:string;value:string;source?:string}){return <div className="kv"><span>{label}{source&&<small className="source">{source}</small>}</span><strong>{value}</strong></div>}
export function Chart({hours,field,kind='line',color='#55d6b2',unit=''}:{hours:Hour[];field:keyof Hour;kind?:'line'|'bar';color?:string;unit?:string}){
  const values=hours.map(h=>{const raw=h[field];return typeof raw==='number'&&Number.isFinite(raw)?raw:null})
  const observed=values.filter((v):v is number=>v!==null)
  if(!observed.length)return <Empty title="No observations yet" description="This metric appears after the gateway records a value."/>
  const max=Math.max(...observed,1),width=700,height=190,pad=18
  const x=(i:number)=>pad+(i*(width-pad*2))/Math.max(values.length-1,1)
  const y=(v:number)=>height-pad-(v/max)*(height-pad*2)
  const segments:string[]=[]
  let current:string[]=[]
  values.forEach((v,i)=>{if(v===null){if(current.length)segments.push(current.join(' '));current=[]}else current.push(`${x(i)},${y(v)}`)})
  if(current.length)segments.push(current.join(' '))
  return <div className="chart-wrap"><svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" aria-label={`${String(field)} over time`}>
    {[.25,.5,.75,1].map(t=><line key={t} x1={pad} x2={width-pad} y1={height-pad-t*(height-pad*2)} y2={height-pad-t*(height-pad*2)} stroke="#253443" strokeDasharray="4 7" />)}
    {kind==='line'?<>{segments.map((points,i)=><polyline key={i} points={points} fill="none" stroke={color} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>)}{values.map((v,i)=>v===null?null:<circle key={i} cx={x(i)} cy={y(v)} r="4" fill={color}><title>{`${hours[i].hour}: ${v.toFixed(1)}${unit}`}</title></circle>)}</>:values.map((v,i)=>{if(v===null)return null;const slot=(width-pad*2)/values.length,bh=(v/max)*(height-pad*2);return <rect key={i} x={pad+i*slot+slot*.16} y={height-pad-bh} width={slot*.68} height={bh} rx="4" fill={color} opacity=".9"><title>{`${hours[i].hour}: ${v.toFixed(1)}${unit}`}</title></rect>})}
  </svg><div className="chart-axis"><span>{new Date(hours[0].hour).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span><span>{new Date(hours[hours.length-1].hour).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span></div></div>
}
export function Distribution({data}:{data:Record<string,number>}){const entries=Object.entries(data).sort((a,b)=>b[1]-a[1]);const total=entries.reduce((n,[,v])=>n+v,0);if(!entries.length)return <Empty title="No distribution yet" description="Provider mix appears after your first request."/>;return <div className="distribution">{entries.map(([key,value])=><div className="distribution-row" key={key}><div><strong>{key}</strong><span>{value} requests · {Math.round(value/total*100)}%</span></div><div className="progress"><span style={{width:`${value/total*100}%`}}/></div></div>)}</div>}
